"""add activate information

Revision ID: f1b02d5d0410
Revises: be982e84c470
Create Date: 2020-08-02 16:44:26.310480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1b02d5d0410'
down_revision = 'be982e84c470'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_activate', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_activate')
    # ### end Alembic commands ###
